/// Generated file. Do not edit.
/// This file is generated by the iFlutter
library;

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'baby_shop_hub';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String LOGO = 'assets/images/LOGO.png';
  static const String LOGO_2 = 'assets/images/logo-2.png';
  static const String LOGO_3 = 'assets/images/logo-3.png';
  // static const String LOGO = 'assets/images/logo.ai';
}
