// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjWgym77N5NPnvIAu7lOb-r1_32rQKqQA',
    appId: '1:702370920561:web:7ce2d60ac31f33bc6f83d0',
    messagingSenderId: '702370920561',
    projectId: 'baby-shop-hub-323ab',
    authDomain: 'baby-shop-hub-323ab.firebaseapp.com',
    storageBucket: 'baby-shop-hub-323ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWCODToaGlejJbpAXWKnclrlL89hbN8EY',
    appId: '1:702370920561:android:a9e6a957c0a5100f6f83d0',
    messagingSenderId: '702370920561',
    projectId: 'baby-shop-hub-323ab',
    storageBucket: 'baby-shop-hub-323ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCIvczPhZwy5qTra3dRfStc6bQl8KmgU0',
    appId: '1:702370920561:ios:059681cefb9df82d6f83d0',
    messagingSenderId: '702370920561',
    projectId: 'baby-shop-hub-323ab',
    storageBucket: 'baby-shop-hub-323ab.appspot.com',
    iosBundleId: 'com.example.babyShopHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCIvczPhZwy5qTra3dRfStc6bQl8KmgU0',
    appId: '1:702370920561:ios:059681cefb9df82d6f83d0',
    messagingSenderId: '702370920561',
    projectId: 'baby-shop-hub-323ab',
    storageBucket: 'baby-shop-hub-323ab.appspot.com',
    iosBundleId: 'com.example.babyShopHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjWgym77N5NPnvIAu7lOb-r1_32rQKqQA',
    appId: '1:702370920561:web:5bd957af0721ab136f83d0',
    messagingSenderId: '702370920561',
    projectId: 'baby-shop-hub-323ab',
    authDomain: 'baby-shop-hub-323ab.firebaseapp.com',
    storageBucket: 'baby-shop-hub-323ab.appspot.com',
  );
}
